version: "3.9"

services:
  health-chatbot:
    build: .
    container_name: health-chatbot
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=your-key-here
    volumes:
      - ./data:/app/data
      - ./faiss_index:/app/faiss_index
